package com.estudochat.ws.providers;


import com.auth0.jwk.JwkException;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
public class JsonWebTokenProviderTeste {

    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void teste() throws JwkException {
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxZYTJXNUJaTzFYNWlnRWxNa1RSTiJ9.eyJnaXZlbl9uYW1lIjoiRGFuaWVsIiwiZmFtaWx5X25hbWUiOiJNZW5lemVzIiwibmlja25hbWUiOiJkYW5pZWxtZW5lemVzZGV2MjUxMiIsIm5hbWUiOiJEYW5pZWwgTWVuZXplcyIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMWFVPS3VMVkdQM2lDMUo5blhnYjVzZGxucHkyQ05oTjNPeDFBU3BmbzhacHl3ekE9czk2LWMiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNy0yMlQyMzo1MTowMS4wMzBaIiwiZW1haWwiOiJkYW5pZWxtZW5lemVzZGV2MjUxMkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9kZXYtdG1zZDFqaDMycHU2dzFzay51cy5hdXRoMC5jb20vIiwiYXVkIjoiSW1WdmxYdmlsSlJlVExJV0JpYkptR255ZzRlZUkxb0UiLCJpYXQiOjE3MjE2OTIyNjYsImV4cCI6MTcyMTcyODI2Niwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDQ2OTk5NzEzNjkzODEzODI5MjUiLCJzaWQiOiJyNEpVTGo0V284aE5mbzJEanYycXdaWHVIVjg0RkQ0aCIsIm5vbmNlIjoiZFZab2F6Y3lTVEpTWjJoNWN6QitOM1l3UjB4T01rOXRVVzR1Tkc5NVJtVTRWalpNWjFsc2JXcGZSZz09In0.Od0lG0UDi1A2DpnJSCLHz9BLouHKCm3z6kCg8QU0L8gvSxvOqCjbehpGsjoOXW9ThV4o0IIwWwvNBmWCee7cdAPVA5pEwM41-LTppZnE7BCSACdarPQwFGTwSMdIPt-VWWJ9N6x03hlBvMPgjpnzFqI09pBqdCG5wXuPIhV84uGvnuw4LRHZfwaHq4WLGCfFyP8uSXsZ-dg1aFNOsbCrNbejfI9DyWaEOIQ4EZLc0eZpO7gXb_Usd6rUKIoia7iX18At2ntcGbz1X_xJ15Bnez5SLcvSEihtLEO81T_qfBwOGsBs5xUA9uh3vUJucnLvxmZoODHMySYchp6g3dkp6Q");
        System.out.println(decoded);
    }
}
